name: Build & Release ChartsView

on:
  workflow_dispatch:

permissions:
  contents: write     # needed to create / update the GitHub Release

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Read version from package.json
        id: get_version
        run: |
          echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

      - name: Build (production)
        run: npm run build

      - name: Zip dist folder
        id: zip
        run: |
          ZIP_NAME=chartsview-${{ steps.get_version.outputs.version }}.zip
          zip -r "$ZIP_NAME" dist
          echo "zip_path=$(pwd)/$ZIP_NAME" >> $GITHUB_OUTPUT

      - name: Create or update GitHub Release & upload ZIP
        uses: ncipollo/release-action@v1
        with:
          tag:              ${{ steps.get_version.outputs.version }}
          commit:           main
          artifacts:        ${{ steps.zip.outputs.zip_path }}
          allowUpdates:     true
          releaseName:      ${{ steps.get_version.outputs.version }}
          body:             |
                              ChartsView plugin build for version ${{ steps.get_version.outputs.version }}
                              _(built via manual dispatch)_
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
