name: Build ChartsView Plugin

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build (production)
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v3
        with:
          name: chartsview-dist
          path: dist/
