name: Build & Release ChartsView

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: Read version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "::set-output name=version::$VERSION"

      - name: Build (production)
        run: npm run build

      - name: Zip plugin files
        id: zip
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          ZIP_NAME=chartsview-${VERSION}.zip
          zip -r "$ZIP_NAME" \
            main.js \
            manifest.json \
            styles.css \
            versions.json
          echo "::set-output name=zip_path::$(pwd)/$ZIP_NAME"

      - name: Create or update GitHub Release & upload ZIP
        uses: ncipollo/release-action@v1
        with:
          tag:          ${{ steps.get_version.outputs.version }}
          allowUpdates: true
          name:         ${{ steps.get_version.outputs.version }}
          body: |
            ChartsView plugin build for version ${{ steps.get_version.outputs.version }}
            _(built via manual dispatch)_
          artifacts:    ${{ steps.zip.outputs.zip_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
