name: Build & Release ChartsView

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write    # needed for create‑release & upload‑release‑asset

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      dist_folder: ${{ steps.build.outputs.dist_folder }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with: { node-version: '18' }

      - run: npm install

      - id: build
        run: |
          npm run build
          echo "::set-output name=dist_folder::$(pwd)/dist"

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:      ${{ github.ref_name }}
          release_name:  ${{ github.ref_name }}
          body:          Automatically built ChartsView ${{ github.ref_name }}
          draft:         false
          prerelease:    false
          # outputs: id, html_url, and upload_url :contentReference[oaicite:0]{index=0}

      - name: Upload plugin ZIP
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url:        ${{ steps.create_release.outputs.upload_url }}
          asset_path:        ${{ needs.build.outputs.dist_folder }}
          asset_name:        chartsview-plugin-${{ github.ref_name }}.zip
          asset_content_type: application/zip
          # upload_url is required and comes from create‑release :contentReference[oaicite:1]{index=1}
