# .github/workflows/build-and-release.yml
name: Build & Release ChartsView

on:
  push:
    tags:
      - 'v*.*.*'          # e.g. v1.2.7.1-jw
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      dist_folder: ${{ steps.build.outputs.dist_folder }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build (production)
        id: build
        run: |
          npm run build
          echo "::set-output name=dist_folder::$(pwd)/dist"

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          # Tag is already created by your push
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            Automatically built ChartsView v${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload plugin files
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ needs.build.outputs.dist_folder }}
          asset_name: chartsview-plugin-${{ github.ref_name }}.zip
          asset_content_type: application/zip
